package Presentacion;

import Controlador.ControlSesionAlumno;
import Controlador.ControlSesionProfesor;

import java.awt.BorderLayout;
import java.awt.Component;
import java.util.Arrays;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author aless
 */
public class frm_AlumnoPrincipal extends javax.swing.JFrame {

    private ControlSesionAlumno sesionAlumno;

    public frm_AlumnoPrincipal() {
        initComponents();
    }

    public frm_AlumnoPrincipal(ControlSesionAlumno controlSesionAlumno) {
        sesionAlumno = controlSesionAlumno;
        sesionAlumno.obtenerDatosAlumnoByIdUsuario();
        initComponents();
        this.setLocationRelativeTo(null);
        labelNombre.setText(sesionAlumno.getAlumno().getNombre());
    }

    public ControlSesionAlumno getSesionAlumno() {
        return sesionAlumno;
    }

    public void setSesionAlumno(ControlSesionAlumno sesionAlumno) {
        this.sesionAlumno = sesionAlumno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVerInformacion = new javax.swing.JButton();
        btnVerNotas = new javax.swing.JButton();
        btnVerActividades = new javax.swing.JButton();
        btnCaminos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        pnPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 600));
        setSize(new java.awt.Dimension(850, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerInformacion.setBackground(new java.awt.Color(51, 51, 255));
        btnVerInformacion.setText("INFORMACION DEL ALUMNO");
        btnVerInformacion.setBorder(null);
        btnVerInformacion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnVerInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerInformacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 250, 80));

        btnVerNotas.setBackground(new java.awt.Color(51, 51, 255));
        btnVerNotas.setText("NOTAS");
        btnVerNotas.setBorder(null);
        btnVerNotas.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnVerNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerNotasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 80));

        btnVerActividades.setBackground(new java.awt.Color(51, 51, 255));
        btnVerActividades.setText("ACTIVIDADES");
        btnVerActividades.setBorder(null);
        btnVerActividades.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnVerActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActividadesActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 80));

        btnCaminos.setBackground(new java.awt.Color(51, 51, 255));
        btnCaminos.setText("VER CAMINOS A SU AULA");
        btnCaminos.setBorder(null);
        btnCaminos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCaminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCaminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 250, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BIENVENIDO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNombre.setToolTipText("");
        labelNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnPrincipal.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(pnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerInformacionActionPerformed
        // TODO add your handling code here:
        panel_InfoAlumno pnInformacion = new panel_InfoAlumno(sesionAlumno);
        mostrarPanel(pnInformacion);
        
    }//GEN-LAST:event_btnVerInformacionActionPerformed

    private void btnVerNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerNotasActionPerformed
        // TODO add your handling code here:
        panel_NotasAlumno panelNotasAlumno = new panel_NotasAlumno(sesionAlumno);

        mostrarPanel(panelNotasAlumno);
    }//GEN-LAST:event_btnVerNotasActionPerformed

    private void btnVerActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActividadesActionPerformed
        panel_Actividades pnCursos = new panel_Actividades(sesionAlumno);
        mostrarPanel(pnCursos);

    }//GEN-LAST:event_btnVerActividadesActionPerformed

    private void btnCaminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminosActionPerformed
        // TODO add your handling code here:
        frm_BuscarCaminos caminos= new frm_BuscarCaminos();
        caminos.setVisible(true);
    }//GEN-LAST:event_btnCaminosActionPerformed

    public void mostrarPanel(JPanel p) {
        p.setSize(600, 600);
        p.setLocation(0, 0);
        //agregamos los paneles al panel "panVariable"
        pnPrincipal.removeAll();
        pnPrincipal.add(p, BorderLayout.CENTER);
        pnPrincipal.revalidate();
        pnPrincipal.repaint();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_AlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_AlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_AlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_AlumnoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_AlumnoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaminos;
    private javax.swing.JButton btnVerActividades;
    private javax.swing.JButton btnVerInformacion;
    private javax.swing.JButton btnVerNotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JPanel pnPrincipal;
    // End of variables declaration//GEN-END:variables
}
