
package Presentacion;

import Controlador.ControlActividades;
import Controlador.ControlSesionAlumno;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aless
 */
public class panel_Actividades extends javax.swing.JPanel {

    ControlActividades controlActividades = new ControlActividades();
    DefaultTableModel tModel;
    public panel_Actividades() {
        initComponents();
    }
    
    public panel_Actividades(ControlSesionAlumno sesion) {
        controlActividades.obtenerCursosAlumno(sesion.getAlumno().getIdAlumno());
        controlActividades.cargarActividades();
        initComponents();
        tModel= (DefaultTableModel) tbActividad.getModel();
        cargarActividades();
        txtCurso.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbActividad = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        txtIdActividad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        btnSeleccionar = new javax.swing.JButton();
        btnCompletarTarea = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbActividad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOTAS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        tbActividad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ACTIVIDAD", "CURSO", "DESCRIPCION"
            }
        ));
        jScrollPane1.setViewportView(tbActividad);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 217, 600, 390));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID ACTIVIDAD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CURSO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DESCRIPCION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        jPanel1.add(txtCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 110, 30));
        jPanel1.add(txtIdActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 30));

        txaDescripcion.setColumns(20);
        txaDescripcion.setRows(5);
        jScrollPane2.setViewportView(txaDescripcion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 270, -1));

        btnSeleccionar.setText("SELECCIONAR");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 130, 30));

        btnCompletarTarea.setText("COMPLETAR TAREA");
        btnCompletarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletarTareaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCompletarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        if(!txtIdActividad.getText().equals("")){
            for(var o : controlActividades.getColaActividades()){
                System.out.println(o.toString());
                if(o.getId()==Integer.parseInt(txtIdActividad.getText())){
                    txtCurso.setText(o.getCurso().getNombreCurso());
                    txaDescripcion.setText(o.getDescripcion());
                }
            }
        }else{
            JOptionPane.showInternalMessageDialog(null, "Ingrese el id de la actividad");
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnCompletarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletarTareaActionPerformed
        // TODO add your handling code here:
        controlActividades.eliminarActividad();
        cargarActividades();
    }//GEN-LAST:event_btnCompletarTareaActionPerformed

    private void cargarActividades(){
        tModel.setRowCount(0);
        controlActividades.cargarActividades();
        for(var o : controlActividades.getColaActividades()){
            tModel.addRow(new Object[]{
                o.getId(),o.getDescripcion(),o.getCurso().getNombreCurso()
            });
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompletarTarea;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbActividad;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtIdActividad;
    // End of variables declaration//GEN-END:variables
}
